# Generated by Django 4.0.6 on 2022-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=50)),
                ('model_price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('color', models.CharField(max_length=20)),
                ('cm', models.PositiveIntegerField()),
            ],
        ),
    ]
